//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ChiTietSuDung
{
    public string MaChiTiet { get; set; }
    public string IDSIM { get; set; }
    public Nullable<System.DateTime> TGBD { get; set; }
    public Nullable<System.DateTime> TGKT { get; set; }
    public Nullable<int> SoPhutSD { get; set; }
    public Nullable<decimal> PhiCuocGoi { get; set; }
    public Nullable<bool> Flag { get; set; }

    public virtual ThongTinSIM ThongTinSIM { get; set; }
}

public partial class GiaCuoc
{
    public string MaGiaCuoc { get; set; }
    public Nullable<System.TimeSpan> TGBD { get; set; }
    public Nullable<System.TimeSpan> TGKT { get; set; }
    public Nullable<decimal> Gia { get; set; }
    public Nullable<bool> Flag { get; set; }
}

public partial class HoaDonDangKy
{
    public string MaHDDK { get; set; }
    public string IDSIM { get; set; }
    public Nullable<decimal> ChiPhiDangKy { get; set; }
    public Nullable<bool> Flag { get; set; }

    public virtual ThongTinSIM ThongTinSIM { get; set; }
}

public partial class HoaDonTinhCuoc
{
    public string MaHDTC { get; set; }
    public string IDSIM { get; set; }
    public Nullable<decimal> PhiThueBao { get; set; }
    public Nullable<decimal> TongTien { get; set; }
    public Nullable<System.DateTime> NgayLapHD { get; set; }
    public Nullable<bool> ThanhToan { get; set; }
    public Nullable<bool> Flag { get; set; }

    public virtual ThongTinSIM ThongTinSIM { get; set; }
}

public partial class KhachHang
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhachHang()
    {
        this.ThongTinSIMs = new HashSet<ThongTinSIM>();
    }

    public string MaKH { get; set; }
    public string TenKH { get; set; }
    public string CMND { get; set; }
    public string Email { get; set; }
    public string NgheNghiep { get; set; }
    public string ChucVu { get; set; }
    public string DiaChi { get; set; }
    public Nullable<bool> Flag { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ThongTinSIM> ThongTinSIMs { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class ThongTinSIM
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ThongTinSIM()
    {
        this.ChiTietSuDungs = new HashSet<ChiTietSuDung>();
        this.HoaDonDangKies = new HashSet<HoaDonDangKy>();
        this.HoaDonTinhCuocs = new HashSet<HoaDonTinhCuoc>();
    }

    public string IDSIM { get; set; }
    public string MaKH { get; set; }
    public Nullable<System.DateTime> NgayDangKy { get; set; }
    public Nullable<System.DateTime> NgayHetHan { get; set; }
    public Nullable<bool> Flag { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ChiTietSuDung> ChiTietSuDungs { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDonDangKy> HoaDonDangKies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<HoaDonTinhCuoc> HoaDonTinhCuocs { get; set; }
    public virtual KhachHang KhachHang { get; set; }
}
